# Generated by Django 4.1.3 on 2022-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('AMD', 'AMD'), ('RUB', 'RUB')], default='USD', max_length=3),
        ),
    ]
