# Generated by Django 4.1.3 on 2022-11-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent', models.PositiveIntegerField(blank=True, verbose_name='Procent_discount')),
                ('code', models.CharField(max_length=10, verbose_name='Id_Coupone')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Discount')),
            ],
        ),
    ]
